code cleanup: removed another >40 lines

diff --git a/aur2ccr-unstable b/aur2ccr-unstable
--- a/aur2ccr-unstable
+++ b/aur2ccr-unstable
@@ -1,5 +1,5 @@
 #!/bin/bash
-# aur2ccr - version 0.6.3
+# aur2ccr - version 0.6.4
 # Pull information from AUR or Arch repos, and make source packages that are ready for uploading to CCR.
 # Usage: aur2ccr [OPTIONS] [PACKAGES]
 # Todo: see README (https://github.com/redhat69/aur2ccr/README)
@@ -15,38 +15,22 @@
 #  the Chakra devs, for making such an awesome distro;
 #  ...and all others who have used aur2ccr or helped in some other way.
 
-# internal settings - not all of these are used yet, but they will be someday
-pname="aur2ccr"
-pver="0.6.3"
-confdir="/etc/aur2ccr"
-lconfdir=~/.aur2ccr # must be unquoted to use ~ substitution
-tmpdir="/tmp/aur2ccr"
-namesconf="names.conf"
-apconf="archrepos.pacman.conf"
+# internal settings - you can modify some of these in aur2ccr.conf
+pname="aur2ccr"         pver="0.6.4"
+confdir="/etc/aur2ccr"  lconfdir=~/.aur2ccr # must be unquoted to use ~ substitution
+tmpdir="/tmp/aur2ccr"   ltmpdir=~/tmp/aur2ccr
+namesconf="names.conf"  apconf="archrepos.pacman.conf"  
 acconf="aur2ccr.conf"
-
 # initialize variables
-startdir="$(pwd)"
-findir="$(pwd)"
-badpkgs=0
-consolidate=0
-edit=0
-addad=0
-install=0
-archrinit=0
-newline='
-'
-RED='\e[1;31m'
-#GREEN='\e[1;32m'
-YELLOW='\e[1;33m'
-BLUE='\e[1;34m'
-PINK='\e[1;35m'
-#CYAN='\e[1;36m'
-#WHITE='\e[1;37m'
-#BLACK='\e[1;39m'
-ENDCOLOR='\e[0m' 
+startdir="$(pwd)"       findir="$(pwd)"
+badpkgs=0               consolidate=0
+edit=0                  addad=0
+install=0               archrinit=0
+newline=$'\n'           
+RED='\e[1;31m'          YELLOW='\e[1;33m'
+BLUE='\e[1;34m'         PINK='\e[1;35m'
+WHITE='\e[1;37m'        ENDCOLOR='\e[0m'        
 programs=( abs autoconf automake bison ccr cmake curl ed flex gawk gcc jshon libtool m4 make makepkg patch pacman )
-
 
 # output formatting functions
 debug() { # echo things when called like 'debug doing stuff...' only when debug=1
@@ -102,6 +86,7 @@ err() { # make aur2ccr's error messages prettier and more unified.
   fi
 }
 
+# other functions
 clean() {  # clean up temp files
   debug "clean('$@')"
   warn "Keyboard interrupt caught, cleaning up..."
@@ -413,11 +398,8 @@ makeccrpkg_r() {    # grab a package from Arch repos, and make it into a CCR-rea
   mkdir -p "$pkgname" || (err "cannot create directory '$startdir/$pkgname'"; logerr $pkgname; exit 1) || return 1
   cd "$pkgname"
   [[ -r "$pkgname.tar.gz" ]] && rm "$pkgname.tar.gz"
-  #
-  #	get Arch package with PKGBUILD, .install, etc, using git or perl script or whatever 
-  #
+  # get Arch package with PKGBUILD, .install, etc, using perl or whatever 
   # extract the package if needed
-  #
   getarchname $pkgname
   [[ "$archname" == 0 ]] && (err "'$pkgname' cannot be found"; exit 1) || return 1
   msg "found '$pkgname' as '$archname'"
@@ -500,17 +482,7 @@ pkgsearch() {  # there is no reason for this function to ever be called except r
   warn "Did you mean: "
   debug "checking aursearch..."
   local aurpkgs="$(aursearch $1)"
-  if [ -n "$aurpkgs" ]; then
-    debug "found aurpkgs, echoing:"
-    echo "$aurpkgs"
-    debug "exiting..."
-    exit 1
-  else
-    debug "grepping pacman..."
-    grepacfull $1
-    debug "exiting..."
-    exit 1
-  fi
+  ([[ -n "$aurpkgs" ]] && (echo "$aurpkgs"; exit 1)) || (grepacfull $1; exit 1) || exit 1
 }
 
 checkaur() {
@@ -521,23 +493,17 @@ checkaur() {
       warn "$1 is marked as out of date in AUR!"
       warn -n "Are you sure you want to continue? [y/N] "
       read ans
-      if [ -z "$ans" -o "$ans" == "n" -o "$ans" == "N" ]; then
+      if [ -z "$ans" -o "$ans" == "n" -o "$ans" == "N" -o "$ans" == "no" ]; then
         warn "Skipping $1"
         return 0
       else
         warn "Continuing. This is a bad idea!"; sleep 3
       fi
     fi
-    if !(makeccrpkg $1); then
-      let badpkgs=$badpkgs+1
-      failedpkgs="$failedpkgs $1"
-    fi
+    makeccrpkg $1 || logerr $1
   elif isinarchr $1; then
     msg "'$1' found in the Arch repos..."
-    if !(makeccrpkg_r $1); then
-      let badpkgs=$badpkgs+1
-      failedpkgs="$failedpkgs $1"
-    fi
+    makeccrpkg_r $1 || logerr $1
   else
     pkgsearch $1
   fi
@@ -667,70 +633,60 @@ debug "main('$@')"
 if [[ $EUID == 0 ]]; then
     err "This script must not be run as root!"
     err "aur2ccr will ask for your password if needed."
-    err "Exiting..."
-    debug "script run as root, exiting"
+    err "Exiting..."; debug "script run as root, exiting"
     exit 1
 fi
-
 # test for important programs that may not be installed 
 for bin in ${programs[@]}; do
   debug "checking for $bin..."
-  if test -x "$(which $bin 2>/dev/null)"; then
+  if [[ -x "$(which $bin 2>/dev/null)" ]]; then
     debug " found"
     continue
   else
-    debug " not found"
-    err "Sorry, you need '$bin' to use this script."
-    err "Try running 'sudo pacman -Sy abs base-devel ccr cmake curl gawk jshon sed'"
+    debug " not found"; err "Sorry, you need '$bin' to use this script."; err "Try running 'sudo pacman -Sy abs base-devel ccr cmake curl gawk jshon sed'"
     exit 1
   fi
 done
 
 # load setting from config files, prefer local over global
-if test -r "$confdir/$acconf"; then
+if [[ -r "$confdir/$acconf" ]]; then
   debug "found global conf, using"
   . "$confdir/$acconf"
-fi; if test -r "$lconfdir/$acconf"; then
+fi; if [[ -r "$lconfdir/$acconf" ]]; then
   debug "found local conf, using"
   . "$lconfdir/$acconf"
 fi # if none exist, just use default values
-# make the temp dir, if it does not already exist
-mkdir -p "$tmpdir"
+mkdir -p "$tmpdir" # make the temp dir, if it does not already exist
 # find other config files, and set variables to point to them- prefer global over local
-if test -r "$confdir/$apconf"; then
+if [[ -r "$confdir/$apconf" ]]; then
   debug "found global pacman conf, using"
   paconf="$confdir/$apconf"
-elif test -r "$lconfdir/$apconf"; then
+elif [[ -r "$lconfdir/$apconf" ]]; then
   debug "found local pacman conf, using"
   paconf="$lconfdir/$apconf"
 else 
   debug "could not find local or global pacman conf, using $tmpdir/pacman.conf.tmp instead"
   printf '[community]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[core]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[extra]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[multilib]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/x86_64\n' > "$tmpdir/pacman.conf.tmp"
   paconf="$tmpdir/pacman.conf.tmp"
-fi; if test -r "$confdir/$namesconf"; then
+fi; if [[ -r "$confdir/$namesconf" ]]; then
   debug "found global names.conf, using"
   namesconf="$confdir/$namesconf"
-elif test -r "$lconfdir/$namesconf"; then
+elif [[ -r "$lconfdir/$namesconf" ]]; then
   debug "found local names.conf, using"
   namesconf="$lconfdir/$namesconf"
 fi
 # fix empty/unset variables to prevent errors
-pname="${pname-aur2ccr}"                 pver="${pver-0.5.7}" 
+pname="${pname-aur2ccr}"                 pver="${pver-0.7}"
 confdir="${confdir-/etc/aur2ccr}"        lconfdir="${lconfdir-~/.aur2ccr}" 
 tmpdir="${tmpdir-/tmp}"                  namesconf="${namesconf-names.conf}"
 apconf="${apconf-archrepos.pacman.conf}" acconf="${acconf-aur2ccr.conf}" 
 startdir="${startdir-$(pwd)}"            findir="${findir-$(pwd)}" 
 consolidate="${consolidate-0}"           edit="${edit-0}" addad="${addad-0}" 
-
-if [ -z "$1" -o "$1" == "--help" -o "$1" == "-h" ]; then  # if no arguments were supplied, print usage info
+if [ -z "$1" -o "$1" == "--help" -o "$1" == "-h" ]; then
   usage
 fi
-
 popopts "$@"
-
-debug "setting trap"
-trap clean INT  # trap keyboard interrupts (^C), in order to clean up temp files
-
+debug "setting trap"; trap clean INT  # trap keyboard interrupts (^C), in order to clean up temp files
 debug "entering 'for' loop"
 for pkgname in $args; do
   debug "checking $pkgname"
@@ -738,7 +694,7 @@ for pkgname in $args; do
     msg "$pkgname is already in CCR or main Chakra repos."
     msg -n "Continue anyway? [y/N] "
     read ans
-    if [ -z "$ans" -o "$ans" == "n" -o "$ans" == "N" ]; then 
+    if [ -z "$ans" -o "$ans" == "n" -o "$ans" == "N" -o "$ans" == "no" ]; then 
       warn "Skipping $pkgname"
       continue
     else 
@@ -748,7 +704,7 @@ for pkgname in $args; do
     msg "$apkgname is already in CCR or main Chakra repos as $cpkgname."
     msg -n "Continue anyway? [y/N] "
     read ans
-    if [ -z "$ans" -o "$ans" == "n" -o "$ans" == "N" ]; then 
+    if [ -z "$ans" -o "$ans" == "n" -o "$ans" == "N" -o "$ans" == "no" ]; then 
       warn "Skipping $pkgname"
       continue
     else 
@@ -758,7 +714,7 @@ for pkgname in $args; do
     msg "$pkgname is already in CCR or main Chakra repos as $vpkgname."
     msg -n "Continue anyway? [y/N] "
     read ans
-    if [ -z "$ans" -o "$ans" == "n" -o "$ans" == "N" ]; then 
+    if [ -z "$ans" -o "$ans" == "n" -o "$ans" == "N" -o "$ans" == "no" ]; then 
       warn "Skipping $pkgname"
       continue
     else 
@@ -768,15 +724,15 @@ for pkgname in $args; do
     checkaur $pkgname
   fi
 done
-if [ -n "$url" ]; then
+if [[ -n "$url" ]]; then
   makeccrpkg_u
-fi; if [ -n "$file" ]; then
+fi; if [[ -n "$file" ]]; then
   makeccrpkg_f
-fi; if [ -n "$pkgdir" ]; then
+fi; if [[ -n "$pkgdir" ]]; then
   makeccrpkg_d
 fi
-
-if [ "$badpkgs" -gt 0 ]; then
+# finish up
+if [[ "$badpkgs" -gt 0 ]]; then
   err "$badpkgs package(s) failed"
   debug "at least $badpkgs packages failed, exiting..."
   exit 1
@@ -787,9 +743,7 @@ else
   warn "will work. Please thoroughly test all packages BEFORE uploading them to CCR."
   warn "Broken packages may be removed without warning."
   exit 0
-fi; if [ -n "$failedpkgs" ]; then 
-  err "The bad package(s) are:"
-  err "$failedpkgs"
-  debug "exiting..."
+fi; if [[ -n "$failedpkgs" ]]; then 
+  err "The bad package(s) are:"; err "$failedpkgs"; debug "exiting..."
   exit 1
 fi
