MAY EAT YOUR HAMSTER! -- Added buggy Arch-pkg-fetching functionality, updated readme, modified several functions. Lots of cleaning up to do still.

diff --git a/aur2ccr b/aur2ccr
--- a/aur2ccr
+++ b/aur2ccr
@@ -1,23 +1,24 @@
 # #!/bin/bash
-# aur2ccr - version 0.5.2
+# aur2ccr - version 0.5.3
 # Pull information from AUR or Arch repos, and make source packages that are ready for uploading to CCR.
 # Usage: aur2ccr [OPTIONS] [PACKAGES]
 # Todo: add the ability to grab packages from Arch repos; 
 #	remove redundant code;
-#	add man page aur2ccr(8);
 #	add ability to check if ${pkgname}-git exists in CCR/Chakra repos;
 #	improve popopts function, to allow options to be used like '-ce';
 #	add the ability to automatically upload packages to CCR (if possible);
 # This script uses the information on converting Arch/AUR files to CCR from http://chakra-linux.org/wiki/index.php/How_to_upload_a_package_to_CCR_when_it_exists_on_Arch_or_Aur
 # Portions of this script may have been taken from "CCR - A Chakra Community Repository helper", which was in turn forked from "Packer by Matthew Bruenig <matthewbruenig@gmail.com>", a GPL3 bash script.
 
-# internal settings
+# internal settings - not all of these are used yet, but they will be someday
 pname="aur2ccr"
-pver="0.5.2"
+pver="0.5.3"
 confdir="/etc/aur2ccr"
+lconfdir="~/.aur2ccr"
 tmpdir="/tmp"
 namesconf="names.conf"
-#AURPCURL="http://aur.archlinux.org/rpc.php?type"
+apconf="archrepos.pacman.conf"
+acconf="aur2ccr.conf"
 
 # initialize variables
 startdir="$(pwd)"
@@ -25,13 +26,14 @@ badpkgs=0
 consolidate=0
 edit=0
 addad=0
+archrinit=0
 
-for bin in ccr ed makepkg packer; do  # test for important programs that may not be installed
+for bin in abs autoconf automake bison ccr ed flex gcc libtool m4 make makepkg patch packer; do  # test for important programs that may not be installed 
   if test -x "$(which $bin 2>/dev/null)"; then
     continue
   else
     echo "Sorry, you need '$bin' to use this script."
-    echo "Try running: sudo pacman -Sy base-devel ccr packer"
+    echo "Try running: sudo pacman -Sy abs base-devel ccr packer"
     exit 1
   fi
 done
@@ -70,27 +72,48 @@ isinaur() {
   fi
 }
 
-isinarchr() {
-  echo "Checking Arch repos..."
-  if [ -z "$archreplist" ]; then
-    printf '[community]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[core]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[extra]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[multilib]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/x86_64\n' > pacman.conf.tmp
-    sudo pacman -Sy --config pacman.conf.tmp # this requires root privileges, so it is not the best solution. If anyone thinks of something better, let me know.
-    if (pacman -Ssq --config pacman.conf.tmp $1 | grep -q "^$1$"); then
-      archreplist="$(pacman -Ssq --config pacman.conf.tmp)"
-      rm -f pacman.conf.tmp
-      sudo pacman -Sy >&2> /dev/null &
-      return 0
-    else
-      archreplist="$(pacman -Ssq --config pacman.conf.tmp)"
-      rm -f pacman.conf.tmp
-      return 1
-    fi
+initarchr() {	# set up the arch repo vars, so we only need to sudo once
+  printf '[community]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[core]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[extra]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[multilib]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/x86_64\n' > pacman.conf.tmp
+  if (sudo pacman -Sy --config pacman.conf.tmp); then
+    areplist=$(pacman --config pacman.conf.tmp -Ssq)
+    afullist=$(pacman --config pacman.conf.tmp -Ss)
+    archrinit=1
+    sudo pacman -Sy >&2> /dev/null
+    rm pacman.conf.tmp
   else
-    if (echo "$archreplist" | grep -q "^$1$"); then
-      return 0
+    echo "aur2ccr: An error occurred while checking Arch repos."
+    rm pacman.conf.tmp
+    exit 1 # you can't call this in an if, (like if initarchr) because the vars will be unset
+  fi
+}
+
+isinarchr() {
+  echo "aur2ccr: Checking Arch repos..."
+  if [ "$archrinit" == 0 ]; then
+    initarchr  
+  fi # we don't need an else, the rest is below and the vars are already set
+
+  if (echo "$areplist" | grep -q "^$1$" ); then
+    return 0
+  else
+    return 1
+  fi # much nicer than the old function
+}
+
+getarchname() {
+  if isinarchr $1; then
+    printf '[community]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[core]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[extra]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[multilib]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/x86_64\n' > pacman.conf.tmp
+    if (sudo pacman -Sy --config pacman.conf.tmp >&2> /dev/null); then
+      archrname=$(pacman -Ss --config pacman.conf.tmp $1 | grep -o "^[^ ]*/$1\s" | sed 's/\s//g')
+      #echo $archrname # for debugging only
+      sudo pacman -Sy >&2> /dev/null #&
     else
+      echo "aur2ccr: pacman failed in function getarchname()"
       return 1
     fi
+   else
+    echo "aur2ccr: '$1' not found in arch repos"
+    return 1
   fi
 }
 
@@ -179,11 +202,8 @@ makeccrpkg() {    # grab a package from AUR, and make it into a CCR-ready src pa
         fi
         popd
       elif isinarchr $pkg; then
-        echo "'$pkg' is in the Arch repos, but this feature is not ready yet."
-        let badpkgs=$badpkgs+1
-        failedpkgs="$failedpkgs $pkgname"
-        return 1
-        #makeccrpkg_r $pkg
+        echo "aur2ccr: '$pkg' is in the Arch repos"
+        makeccrpkg_r $pkg
       else
         echo "aur2ccr: Sorry, dependency '$pkg' cannot be found."
       fi
@@ -238,6 +258,40 @@ makeccrpkg_r() {    # grab a package from Arch repos, and make it into a CCR-rea
   #	get Arch package with PKGBUILD, .install, etc, using git or perl script or whatever 
   #
   # extract the package if needed
+  #
+  if !(getarchname $pkgname); then
+    echo "aur2ccr: '$pkgname' cannot be found"
+    return 1
+  fi
+  #countdown 20
+  getarchname $pkgname
+  if [ -z "$archrname" ]; then
+    echo "aur2ccr: Something bad happened! (Sorry about your hamster...)"
+    let badpkgs=$badpkgs+1
+    return 1
+  fi
+  echo "aur2ccr: found '$pkgname' as '$archrname'"
+  if (sudo abs "$archrname"); then
+    rm -rf "./$pkgname"
+    if (sudo mv "/var/abs/$archrname" "./$pkgname"); then
+      if (sudo chown -hR $USER:$USER "./$pkgname"); then
+        echo "aur2ccr: $pkgname info retrieved from Arch repos successfully"
+      else
+        echo "aur2ccr: chown failed"
+      fi
+    else
+      echo "aur2ccr: could not move /var/abs/$archrname to working dir"
+      let badpkgs=$badpkgs+1
+      return 1
+    fi
+  else
+    echo "aur2ccr: abs failed"
+    let badpkgs=$badpkgs+1
+    return 1
+  fi
+  #
+  #  ^ this is a quick fix ^
+  #
   cd "$pkgname" #this should cd to wherever the stuff above put the PKGBUILD
   depsnotinccr=0
   if [ "$edit" -eq 1 ]; then
@@ -269,11 +323,8 @@ makeccrpkg_r() {    # grab a package from Arch repos, and make it into a CCR-rea
         fi
         popd
       elif isinarchr $pkg; then
-        echo "'$pkg' is in the Arch repos, but this feature is not ready yet."
-        let badpkgs=$badpkgs+1
-        failedpkgs="$failedpkgs $pkgname"
-        return 1
-        #makeccrpkg_r $pkg
+        echo "aur2ccr: '$pkg' is in the Arch repos"
+        makeccrpkg_r $pkg
       else
         echo "aur2ccr: Sorry, dependency '$pkg' cannot be found."
       fi
@@ -372,11 +423,8 @@ makeccrpkg_u() {
         fi
         popd
       elif isinarchr $pkg; then
-        echo "'$pkg' is in the Arch repos, but this feature is not ready yet."
-        let badpkgs=$badpkgs+1
-        failedpkgs="$failedpkgs $pkgname"
-        return 1
-        #makeccrpkg_r $pkg
+        echo "aur2ccr: '$pkg' is in the Arch repos"
+        makeccrpkg_r $pkg
       else
         echo "aur2ccr: Sorry, dependency '$pkg' cannot be found."
       fi
@@ -474,11 +522,8 @@ makeccrpkg_f() {
         fi
         popd
       elif isinarchr $pkg; then
-        echo "'$pkg' is in the Arch repos, but this feature is not ready yet."
-        let badpkgs=$badpkgs+1
-        failedpkgs="$failedpkgs $pkgname"
-        return 1
-        #makeccrpkg_r $pkg
+        echo "aur2ccr: '$pkg' is in the Arch repos"
+        makeccrpkg_r $pkg
       else
         echo "aur2ccr: Sorry, dependency '$pkg' cannot be found."
       fi
@@ -539,28 +584,23 @@ aursearch() {  # uses 'packer'
   packer --auronly -Ss $1
 }
 
-pkgsearch() {
-  # this function should NEVER be called except right after isinarchr!
+pkgsearch() { # there is no reason for this function to ever be called except right after isinarchr returns 1
   echo "Package '$1' not found in AUR or Arch repos."
   echo "Did you mean: "
   local aurpkgs="$(aursearch $1)"
   if [ -n "$aurpkgs" ]; then
     echo "$aurpkgs"
-    sudo pacman -Sy >&2> /dev/null &
-    rm -f pacman.conf.tmp
     exit 1
   else
-    printf '[community]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[core]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[extra]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/i686\n\n[multilib]\nServer = http://ftp.osuosl.org/pub/archlinux/$repo/os/x86_64\n' > pacman.conf.tmp
-    local archpkgs="$(pacman -Ss $1 --config pacman.conf.tmp)"
+    if [ "$archrinit" == 0 ]; then
+      initarchr
+    fi
+    local archpkgs=$(echo "$afullist" | grep -i $1) # this is wrong, so I will have to change it later.
     if [ -n "$archpkgs" ]; then
       echo "$archpkgs"
-      sudo pacman -Sy >&2> /dev/null &
-      rm -f pacman.conf.tmp
       exit 1
     else
       echo " (nothing found)"
-      sudo pacman -Sy >&2> /dev/null &
-      rm -f pacman.conf.tmp
       exit 1
     fi
   fi
@@ -574,10 +614,8 @@ checkaur() {
     fi
   else
     if isinarchr $1; then
-      echo "'$1' is in Arch repos, but this feature is not yet ready."
-      let badpkgs=$badpkgs+1
-      failedpkgs="$failedpkgs $1"
-    #	makeccrpkg_r $1
+      echo "aur2ccr: '$pkg' is in the Arch repos"
+      makeccrpkg_r $1
 #	  elif isinaur "$(namelookup $1)"; then
 #	    if !(makeccrpkg "$apkgname"); then
 #	      let badpkgs=$badpkgs+1
