added several features to -unstable

diff --git a/aur2ccr-unstable b/aur2ccr-unstable
--- a/aur2ccr-unstable
+++ b/aur2ccr-unstable
@@ -27,6 +27,7 @@ acconf="aur2ccr.conf"
 
 # initialize variables
 startdir="$(pwd)"
+findir="$(pwd)"
 badpkgs=0
 consolidate=0
 edit=0
@@ -34,15 +35,16 @@ addad=0
 archrinit=0
 newline='
 '
-BLACK='\e[1;39m'
-GREEN='\e[1;32m'
-PINK='\e[1;35m'
-CYAN='\e[1;36m'
-BLUE='\e[1;34m'
-YELLOW='\e[1;33m'
 RED='\e[1;31m'
+#GREEN='\e[1;32m'
+YELLOW='\e[1;33m'
+BLUE='\e[1;34m'
+PINK='\e[1;35m'
+#CYAN='\e[1;36m'
+WHITE='\e[1;37m'
+#BLACK='\e[1;39m'
 ENDCOLOR='\e[0m' 
-programs=( abs autoconf automake bison ccr ed flex gcc libtool m4 make makepkg patch packer )
+programs=( abs autoconf automake bison ccr ed flex gcc libtool m4 make makepkg patch packer pacman )
 
 
 # output formatting functions
@@ -143,6 +145,7 @@ grepacfull() {  # grep the output of pacman -Ss in a useful manner
       fi
     fi
   done
+  IFS=" "
   if [ "$ret" == 0 ]; then
     echo " (nothing found)"
   fi
@@ -179,7 +182,6 @@ isinaur() {
   fi
 }
 
-
 isinarchr() {
   debug "isinarchr('$@')"
   msg "Checking Arch repos..."
@@ -204,7 +206,7 @@ getarchname() {
   fi
 }
 
-depends() {
+depends() {  # get the dependencies from the PKGBUILD - may not work with multi-line depends
   debug "depends('$@')"
   depends=$(grep '^depends=' PKGBUILD | sed "s/depends=(['\"]\(.*\)['\"])/\1/; s/['\"]//g")
   depends="$depends $(grep '^makedepends=' PKGBUILD | sed "s/makedepends=(['\"]\(.*\)['\"])/\1/; s/['\"]//g")"
@@ -220,18 +222,12 @@ depends() {
   done
 }
 
-addmaintainer() { # this is wrong, I need to beef up the function a little.
+addmaintainer() {  # change maintainer info in the PKGBUILD
   debug "addmaintainer('$@')"
-#  if  
-#    
-#  fi
-  ed -s PKGBUILD << EOF | sed 's/#\sContributer/ Previous Maintainer/'
-1s/Maintainer/Contributer
-1i
-# Maintainer: $1
-.
-wq
-EOF
+  sed -in 's/^# Maintainer: /# Contributer: /' PKGBUILD
+  if !(printf "# Maintainer: ${maintainer}\n$(cat PKGBUILD)" > PKGBUILD.1 && mv PKGBUILD.1 PKGBUILD); then
+    return 1
+  fi
 }
 
 addad() {
@@ -242,6 +238,36 @@ addad() {
 .
 wq
 EOF
+}
+
+uchksums() {  # update checksums with 'makepkg -gf'
+  debug "uchksums($@)"
+  sums="$(makepkg -gf)"
+  stype="$(echo $sums | grep -o "^..*sums=")"
+  if (echo "$sums" | grep -q "^$stype"); then
+    if (grep -Pq "(^$stype.*\)|^${stype}[^\(])" PKGBUILD); then # if all on one line
+      if (sed -i "s/^$stype.*/$sums/" PKGBUILD); then
+        return 0
+      else
+        err "sed failed while updating checksums"
+        return 1
+      fi
+    elif (grep -q "^$stype" PKGBUILD); then
+      stype="$(echo "$stype" | sed 's/=//; s/\s//g')"
+      debug "awking..."
+      local new="$(awk -v "newsums=$sums" -v "stype=$stype" '$1 ~ stype { t = 1; } t == 1 { if ($0 ~ "\)") { t = 0; print(newsums); next; } next; } { print; }' PKGBUILD 2>/dev/null)" # sheesh. awk courtesy of pr3d4t0r, I haven't a clue how it works.
+      debug "sending awk output to PKGBUILD..."
+      echo "$new" > PKGBUILD
+      return 0
+    elif [ -z "$sums" ]; then
+      return 0
+    else
+      return 1
+    fi
+  else
+    err "something went wrong while updating checksums"
+    return 1
+  fi
 }
 
 dotherest() {
@@ -260,6 +286,12 @@ dotherest() {
   debug "if \$addad then addad..."
   if [ "$addad" == 1 ]; then
     addad
+  fi
+  debug "if uchksums..."
+  if uchksums; then
+    msg "checksums for $pkgname updated"
+  else
+    warn "checksums for $pkgname could not be updated!"
   fi
   debug "if \$edit, then edit..."
   if [ "$edit" -eq 1 ]; then
@@ -346,13 +378,12 @@ dotherest() {
     warn "Running 'makepkg -s' on this package will fail, so we cannot test it now."
     warn "Please test the final .src.tar.gz package manually with ccr."
   fi
-  makepkg -gf
   if (makepkg --source -f); then
     msg "Package '$pkgname' built successfully."
     if [ "$consolidate" -eq 1 ]; then
       pkgpkg="$(ls $pkgname*.src.tar.gz)"
-      mv $pkgpkg "$startdir"
-      msg "$pkgpkg moved to $startdir"
+      mv $pkgpkg "$findir"
+      msg "$pkgpkg moved to $findir"
     fi
   else
     err "Some error occurred, check the $pkgname PKGBUILD in $(pwd)"
@@ -471,9 +502,12 @@ makeccrpkg_u() {
     failedpkgs="$failedpkgs $pkgname"
     return 1
   fi
+
   if dotherest "$pkgname"; then
     return 0
   else
+    let badpkgs=$badpkgs+1
+    failedpkgs="$failedpkgs $pkgname"
     return 1
   fi
 }
@@ -509,10 +543,51 @@ makeccrpkg_f() {
   if dotherest "$pkgname"; then
     return 0
   else
+    let badpkgs=$badpkgs+1
+    failedpkgs="$failedpkgs $pkgname"
     return 1
   fi
 }
 
+makeccrpkg_d() {  # uses $pkgdir as directory containting PKGBUILD. (argument to -d)
+  debug "makeccrpkg_d('$@')"
+  cd "$startdir"
+  local pkgname="$(basename "$pkgdir")"
+  if test -d "$pkgdir"; then
+    cd "$pkgdir"
+  else
+    err "$pkgdir is not a directory or does not exist"
+    let badpkgs=$badpkgs+1
+    failedpkgs="$failedpkgs $pkgname"
+    return 1
+  fi; if ! test -r "PKGBUILD"; then
+    err "'$pkgdir/PKGBUILD' cannot be opened or does not exist"
+    let badpkgs=$badpkgs+1
+    failedpkgs="$failedpkgs $pkgname"
+    return 1
+  fi
+  cd "$startdir"
+  if !(mkdir -p "$pkgname"); then
+    err "cannot create directory '$startdir/$pkgname'"
+    let badpkgs=$badpkgs+1
+    failedpkgs="$failedpkgs $pkgname"
+    return 1
+  fi; if !(cp -r "$pkgdir" "$pkgname/"); then
+    err "cannot copy files from '$pkgdir'"
+    let badpkgs=$badpkgs+1
+    failedpkgs="$failedpkgs $pkgname"
+    return 1
+  fi
+  cd "$pkgname/$pkgname"
+
+  if dotherest "$pkgname"; then
+    return 0
+  else
+    let badpkgs=$badpkgs+1
+    failedpkgs="$failedpkgs $pkgname"
+    return 1
+  fi
+}
 
 namelookup() {  # see https://github.com/redhat69/aur2ccr/issues/1
   debug "namelookup('$@')"
@@ -602,6 +677,10 @@ usage() {
   echo "  -c			move all CCR source packages into the working directory"
   echo "  -f <file>		create a CCR source package from source package <file>"
   echo "  -u <URL>		... or from an AUR/CCR-compatible source package at <URL>"
+  echo "  -d <dir>		... or from a PKGBUILD and (optional) other files in <dir>"
+  echo "  -C <newdir>		use <newdir> as the working directory instead of the current dir"
+  echo "  -t			use '$tmpdir' as the build directory instead of the current dir"
+  echo "   			(all finished src packages will be moved into the working dir, like -c)"
   echo "  -h			display this help and exit"
   echo "  -v			print version information and exit"
   echo 
@@ -625,6 +704,15 @@ popopts() {  # populate variables, enumerate options and arguments -- crappy - i
       url="$arg"
       isurl=0
       continue
+    elif [ -n "$isdir" -a "$isdir" == 1 ]; then 
+      pkgdir="$arg"
+      isdir=0
+      continue
+    elif [ -n "$iscdir" -a "$iscdir" == 1 ]; then 
+      startdir="$arg"
+      findir="$arg"
+      iscdir=0
+      continue
     elif [ -n "$ismaint" -a "$ismaint" == 1 ]; then
       maintainer="$arg"
       ismaint=0
@@ -640,6 +728,13 @@ popopts() {  # populate variables, enumerate options and arguments -- crappy - i
       isfile=1
     elif [ -n "$arg" -a "$arg" == "-u" ]; then
       isurl=1
+    elif [ -n "$arg" -a "$arg" == "-d" ]; then
+      isdir=1
+    elif [ -n "$arg" -a "$arg" == "-C" ]; then
+      iscdir=1
+    elif [ -n "$arg" -a "$arg" == "-t" ]; then
+      usetdir=1
+      consolidate=1
     elif [ -n "$arg" -a "$arg" == "-h" ]; then
       usage
     elif [ -n "$arg" -a "$arg" == "-v" ]; then
@@ -651,7 +746,10 @@ popopts() {  # populate variables, enumerate options and arguments -- crappy - i
       args="$args $arg"
     fi
   done
-  if [ -z "$args" -a -z "$url" -a -z "$file" ]; then 
+  if [ -n "$usetdir" -a "$usetdir" == 1 ]; then
+    startdir="$tmpdir"
+  fi
+  if [ -z "$args" -a -z "$url" -a -z "$file" -a -z "$pkgdir" ]; then 
     err "You did not specify any packages to build"
     err "There is nothing to do. Exiting..."
     exit 1
@@ -714,6 +812,8 @@ if [ -n "$url" ]; then
   makeccrpkg_u
 fi; if [ -n "$file" ]; then
   makeccrpkg_f
+fi; if [ -n "$pkgdir" ]; then
+  makeccrpkg_d
 fi
 
 if [ "$badpkgs" -gt 0 ]; then
@@ -723,6 +823,9 @@ if [ "$badpkgs" -gt 0 ]; then
 else
   msg "$badpkgs package(s) failed"
   debug "0 pkgs failed, exiting..."
+  warn "Remember, just because aur2ccr seems to have succeeded, does not mean the package(s)"
+  warn "will work. Please thoroughly test all packages BEFORE uploading them to CCR."
+  warn "Broken packages may be removed without warning."
   exit 0
 fi; if [ -n "$failedpkgs" ]; then 
   err "The bad package(s) are:"
